### PR TITLE
Updates Twirl with latest updates from origin Play TE

### PR DESCRIPTION
**Pull request by 4lex1v**
I've also did some quick code style fixes and updated build dependencies. Twirl updated to [this](https://github.com/playframework/playframework/commit/6951db69161a6d4d6874bbf99cd087c4707519d1) commit

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, for doing another round of updates. I've just finished a merge that tried to make your older changes also work for Scala 2.9. I'll see if that still works for this one.

**Comment by jrudolph** [comment]
Do you know in how far this version is still compatible with the old one?

**Comment by 4lex1v** [comment]
They did some API changes and improvements, but code still should be compatible with scala 2.9, i didn't notice any 2.10 features. They have little changes in the compiler, e.g [my previous](https://github.com/4lex1v/twirl/blob/abc5b88643a9aea80610654bb2922f3aa086b432/twirl-compiler/src/main/scala/twirl/compiler/TwirlCompiler.scala#L178) twirl version and [latest](https://github.com/playframework/playframework/blob/ac233158fffcdcc35d9906436ab414f7515fd620/framework/src/templates-compiler/src/main/scala/play/templates/ScalaTemplateCompiler.scala#L173) Play version). Although it's easy to make it fully compatible, i didn't want to touch original play implementation of the compiler or it would be harder to update it further.

**Comment by jrudolph** [comment]
From looking at [the history](https://github.com/playframework/playframework/commits/ac233158fffcdcc35d9906436ab414f7515fd620/framework/src/templates-compiler/src/main/scala/play/templates/ScalaTemplateCompiler.scala) it seems they merely changed the formatting and made small changes to the runtime classes. My main concern was that there were some changes that changed the syntax itself but it seems that didn't happen at all. Now I'll "just" have to do a re-merge of your changes and see where this will lead us to...

**Comment by jrudolph** [comment]
It seems I spoke to soon, there's lots more history that was hidden behind file renamings, so there have been more changes.

**Comment by 4lex1v** [comment]
Well, templates (scala.html files) in tests doesn't have any changes in syntax, so, i guess, there were no changes with template syntax.

**Comment by jrudolph** [comment]
I incorporated your commits into the below sbt-0.13 branch and added a bit of compatibility stuff so that it also compiles for Scala 2.9.x. Can you try the new `0.7.0-SNAPSHOT` version? You'll probably have to add this resolver to `plugins.sbt`:

``` scala
resolvers += Classpaths.sbtPluginSnapshots
```

sbt 0.13 branch: https://github.com/spray/twirl/commits/i/15/try-to-convert-to-sbt-0.13

**Pull request merged**
